#!/bin/bash

##################################
#
# Script that prints the numbers
# divisible by 3 and 5 but not 15
# between 1 & 100
#
##################################


for i in {1..100}; do
  if (( (i % 3 == 0 || i % 5 == 0) && i % 15 != 0 ))
  then
    echo $i
  fi;
done

